/*
 * generated by Xtext 2.10.0
 */
package be.uantwerpen.ansymo.missionspecification


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MissionSpecificationStandaloneSetup extends MissionSpecificationStandaloneSetupGenerated {

	def static void doSetup() {
		new MissionSpecificationStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
