/*
 * generated by Xtext 2.10.0
 */
package be.uantwerpen.ansymo.missionspecification.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMissionSpecificationScopeProvider extends DelegatingScopeProvider {
}
