/**
 * generated by Xtext 2.10.0
 */
package be.uantwerpen.ansymo.missionspecification.missionSpecification.impl;

import be.uantwerpen.ansymo.missionspecification.missionSpecification.CoveredPointsAssociation;
import be.uantwerpen.ansymo.missionspecification.missionSpecification.MissionSpecificationPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Covered Points Association</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class CoveredPointsAssociationImpl extends AssociationImpl implements CoveredPointsAssociation
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CoveredPointsAssociationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MissionSpecificationPackage.Literals.COVERED_POINTS_ASSOCIATION;
  }

} //CoveredPointsAssociationImpl
