/**
 * generated by Xtext 2.10.0
 */
package be.uantwerpen.ansymo.missionspecification.missionSpecification.impl;

import be.uantwerpen.ansymo.missionspecification.missionSpecification.FinishedTasksAssociation;
import be.uantwerpen.ansymo.missionspecification.missionSpecification.MissionSpecificationPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Finished Tasks Association</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class FinishedTasksAssociationImpl extends AssociationImpl implements FinishedTasksAssociation
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FinishedTasksAssociationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MissionSpecificationPackage.Literals.FINISHED_TASKS_ASSOCIATION;
  }

} //FinishedTasksAssociationImpl
