/*
 * generated by Xtext 2.10.0
 */
package be.uantwerpen.ansymo.missionspecification.ui.tests;

import be.uantwerpen.ansymo.missionspecification.ui.internal.MissionspecificationActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class MissionSpecificationUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MissionspecificationActivator.getInstance().getInjector("be.uantwerpen.ansymo.missionspecification.MissionSpecification");
	}

}
