/**
 * generated by Xtext 2.10.0
 */
package be.uantwerpen.ansymo.missionspecification.missionSpecification;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Covered Points Association</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see be.uantwerpen.ansymo.missionspecification.missionSpecification.MissionSpecificationPackage#getCoveredPointsAssociation()
 * @model
 * @generated
 */
public interface CoveredPointsAssociation extends Association
{
} // CoveredPointsAssociation
