/**
 * generated by Xtext 2.10.0
 */
package be.uantwerpen.ansymo.missionspecification.missionSpecification;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Finished Tasks Association</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see be.uantwerpen.ansymo.missionspecification.missionSpecification.MissionSpecificationPackage#getFinishedTasksAssociation()
 * @model
 * @generated
 */
public interface FinishedTasksAssociation extends Association
{
} // FinishedTasksAssociation
