/**
 * generated by Xtext 2.10.0
 */
package be.uantwerpen.ansymo.missionspecification.missionSpecification;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Global Scope</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see be.uantwerpen.ansymo.missionspecification.missionSpecification.MissionSpecificationPackage#getGlobalScope()
 * @model
 * @generated
 */
public interface GlobalScope extends Scope
{
} // GlobalScope
