/**
 * generated by Xtext 2.10.0
 */
package be.uantwerpen.ansymo.missionspecification.missionSpecification;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Less Than Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see be.uantwerpen.ansymo.missionspecification.missionSpecification.MissionSpecificationPackage#getLessThanCondition()
 * @model
 * @generated
 */
public interface LessThanCondition extends BinaryExpression
{
} // LessThanCondition
