/**
 * generated by Xtext 2.10.0
 */
package be.uantwerpen.ansymo.missionspecification.missionSpecification;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see be.uantwerpen.ansymo.missionspecification.missionSpecification.MissionSpecificationPackage
 * @generated
 */
public interface MissionSpecificationFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MissionSpecificationFactory eINSTANCE = be.uantwerpen.ansymo.missionspecification.missionSpecification.impl.MissionSpecificationFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Mission Specification</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Mission Specification</em>'.
   * @generated
   */
  MissionSpecification createMissionSpecification();

  /**
   * Returns a new object of class '<em>Property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Property</em>'.
   * @generated
   */
  Property createProperty();

  /**
   * Returns a new object of class '<em>Scope</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Scope</em>'.
   * @generated
   */
  Scope createScope();

  /**
   * Returns a new object of class '<em>Pattern</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pattern</em>'.
   * @generated
   */
  Pattern createPattern();

  /**
   * Returns a new object of class '<em>Occurence</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Occurence</em>'.
   * @generated
   */
  Occurence createOccurence();

  /**
   * Returns a new object of class '<em>Universality</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Universality</em>'.
   * @generated
   */
  Universality createUniversality();

  /**
   * Returns a new object of class '<em>Absence</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Absence</em>'.
   * @generated
   */
  Absence createAbsence();

  /**
   * Returns a new object of class '<em>Existence</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Existence</em>'.
   * @generated
   */
  Existence createExistence();

  /**
   * Returns a new object of class '<em>Bounded Existence</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Bounded Existence</em>'.
   * @generated
   */
  BoundedExistence createBoundedExistence();

  /**
   * Returns a new object of class '<em>Order</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Order</em>'.
   * @generated
   */
  Order createOrder();

  /**
   * Returns a new object of class '<em>Precedence</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Precedence</em>'.
   * @generated
   */
  Precedence createPrecedence();

  /**
   * Returns a new object of class '<em>Response</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Response</em>'.
   * @generated
   */
  Response createResponse();

  /**
   * Returns a new object of class '<em>Proposition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Proposition</em>'.
   * @generated
   */
  Proposition createProposition();

  /**
   * Returns a new object of class '<em>Atomic Proposition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Atomic Proposition</em>'.
   * @generated
   */
  AtomicProposition createAtomicProposition();

  /**
   * Returns a new object of class '<em>Boolean Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Boolean Expression</em>'.
   * @generated
   */
  BooleanExpression createBooleanExpression();

  /**
   * Returns a new object of class '<em>Binary Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Binary Expression</em>'.
   * @generated
   */
  BinaryExpression createBinaryExpression();

  /**
   * Returns a new object of class '<em>Unary Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Unary Expression</em>'.
   * @generated
   */
  UnaryExpression createUnaryExpression();

  /**
   * Returns a new object of class '<em>Instance</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Instance</em>'.
   * @generated
   */
  Instance createInstance();

  /**
   * Returns a new object of class '<em>Instance Decl</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Instance Decl</em>'.
   * @generated
   */
  InstanceDecl createInstanceDecl();

  /**
   * Returns a new object of class '<em>Instance Ref</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Instance Ref</em>'.
   * @generated
   */
  InstanceRef createInstanceRef();

  /**
   * Returns a new object of class '<em>Association</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Association</em>'.
   * @generated
   */
  Association createAssociation();

  /**
   * Returns a new object of class '<em>Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Type</em>'.
   * @generated
   */
  Type createType();

  /**
   * Returns a new object of class '<em>Attribute</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Attribute</em>'.
   * @generated
   */
  Attribute createAttribute();

  /**
   * Returns a new object of class '<em>Arithmetic Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Arithmetic Expression</em>'.
   * @generated
   */
  ArithmeticExpression createArithmeticExpression();

  /**
   * Returns a new object of class '<em>Int Literal</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Int Literal</em>'.
   * @generated
   */
  IntLiteral createIntLiteral();

  /**
   * Returns a new object of class '<em>Real Literal</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Real Literal</em>'.
   * @generated
   */
  RealLiteral createRealLiteral();

  /**
   * Returns a new object of class '<em>String Literal</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>String Literal</em>'.
   * @generated
   */
  StringLiteral createStringLiteral();

  /**
   * Returns a new object of class '<em>Bool Literal</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Bool Literal</em>'.
   * @generated
   */
  BoolLiteral createBoolLiteral();

  /**
   * Returns a new object of class '<em>Global Scope</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Global Scope</em>'.
   * @generated
   */
  GlobalScope createGlobalScope();

  /**
   * Returns a new object of class '<em>Before Scope</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Before Scope</em>'.
   * @generated
   */
  BeforeScope createBeforeScope();

  /**
   * Returns a new object of class '<em>After Scope</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>After Scope</em>'.
   * @generated
   */
  AfterScope createAfterScope();

  /**
   * Returns a new object of class '<em>Between Scope</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Between Scope</em>'.
   * @generated
   */
  BetweenScope createBetweenScope();

  /**
   * Returns a new object of class '<em>After Until Scope</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>After Until Scope</em>'.
   * @generated
   */
  AfterUntilScope createAfterUntilScope();

  /**
   * Returns a new object of class '<em>Mock Proposition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Mock Proposition</em>'.
   * @generated
   */
  MockProposition createMockProposition();

  /**
   * Returns a new object of class '<em>Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Condition</em>'.
   * @generated
   */
  Condition createCondition();

  /**
   * Returns a new object of class '<em>Equals Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Equals Condition</em>'.
   * @generated
   */
  EqualsCondition createEqualsCondition();

  /**
   * Returns a new object of class '<em>Less Than Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Less Than Condition</em>'.
   * @generated
   */
  LessThanCondition createLessThanCondition();

  /**
   * Returns a new object of class '<em>Greater Than Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Greater Than Condition</em>'.
   * @generated
   */
  GreaterThanCondition createGreaterThanCondition();

  /**
   * Returns a new object of class '<em>Not Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Not Condition</em>'.
   * @generated
   */
  NotCondition createNotCondition();

  /**
   * Returns a new object of class '<em>Tasks Association</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Tasks Association</em>'.
   * @generated
   */
  TasksAssociation createTasksAssociation();

  /**
   * Returns a new object of class '<em>Team Association</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Team Association</em>'.
   * @generated
   */
  TeamAssociation createTeamAssociation();

  /**
   * Returns a new object of class '<em>Robots Association</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Robots Association</em>'.
   * @generated
   */
  RobotsAssociation createRobotsAssociation();

  /**
   * Returns a new object of class '<em>Current Task Association</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Current Task Association</em>'.
   * @generated
   */
  CurrentTaskAssociation createCurrentTaskAssociation();

  /**
   * Returns a new object of class '<em>Covered Tasks Association</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Covered Tasks Association</em>'.
   * @generated
   */
  CoveredTasksAssociation createCoveredTasksAssociation();

  /**
   * Returns a new object of class '<em>Todo Tasks Association</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Todo Tasks Association</em>'.
   * @generated
   */
  TodoTasksAssociation createTodoTasksAssociation();

  /**
   * Returns a new object of class '<em>Finished Tasks Association</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Finished Tasks Association</em>'.
   * @generated
   */
  FinishedTasksAssociation createFinishedTasksAssociation();

  /**
   * Returns a new object of class '<em>Performing Action Association</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Performing Action Association</em>'.
   * @generated
   */
  PerformingActionAssociation createPerformingActionAssociation();

  /**
   * Returns a new object of class '<em>In Association</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>In Association</em>'.
   * @generated
   */
  InAssociation createInAssociation();

  /**
   * Returns a new object of class '<em>Current Position Association</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Current Position Association</em>'.
   * @generated
   */
  CurrentPositionAssociation createCurrentPositionAssociation();

  /**
   * Returns a new object of class '<em>Home Association</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Home Association</em>'.
   * @generated
   */
  HomeAssociation createHomeAssociation();

  /**
   * Returns a new object of class '<em>Task Area Association</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Task Area Association</em>'.
   * @generated
   */
  TaskAreaAssociation createTaskAreaAssociation();

  /**
   * Returns a new object of class '<em>Covered Points Association</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Covered Points Association</em>'.
   * @generated
   */
  CoveredPointsAssociation createCoveredPointsAssociation();

  /**
   * Returns a new object of class '<em>Todo Points Association</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Todo Points Association</em>'.
   * @generated
   */
  TodoPointsAssociation createTodoPointsAssociation();

  /**
   * Returns a new object of class '<em>Finished Points Association</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Finished Points Association</em>'.
   * @generated
   */
  FinishedPointsAssociation createFinishedPointsAssociation();

  /**
   * Returns a new object of class '<em>Points Association</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Points Association</em>'.
   * @generated
   */
  PointsAssociation createPointsAssociation();

  /**
   * Returns a new object of class '<em>Initial Position Association</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Initial Position Association</em>'.
   * @generated
   */
  InitialPositionAssociation createInitialPositionAssociation();

  /**
   * Returns a new object of class '<em>Reference Association</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Reference Association</em>'.
   * @generated
   */
  ReferenceAssociation createReferenceAssociation();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  MissionSpecificationPackage getMissionSpecificationPackage();

} //MissionSpecificationFactory
