/*
 * generated by Xtext 2.10.0
 */
package be.uantwerpen.ansymo.missionspecification.ui;

import be.uantwerpen.ansymo.missionspecification.ui.internal.MissionspecificationActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MissionSpecificationExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return MissionspecificationActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return MissionspecificationActivator.getInstance().getInjector(MissionspecificationActivator.BE_UANTWERPEN_ANSYMO_MISSIONSPECIFICATION_MISSIONSPECIFICATION);
	}
	
}
