/**
 * generated by Xtext 2.10.0
 */
package be.uantwerpen.ansymo.missionspecification.ui;

import be.uantwerpen.ansymo.missionspecification.ui.AbstractMissionSpecificationUiModule;
import be.uantwerpen.ansymo.missionspecification.ui.editor.syntaxcoloring.MissionSpecificationHighlightingConfiguration;
import be.uantwerpen.ansymo.missionspecification.ui.editor.syntaxcoloring.MissionSpecificationSemanticHighlightingCalculator;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.eclipse.xtext.ide.editor.syntaxcoloring.ISemanticHighlightingCalculator;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class MissionSpecificationUiModule extends AbstractMissionSpecificationUiModule {
  public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration() {
    return MissionSpecificationHighlightingConfiguration.class;
  }
  
  /**
   * def Class<? extends AbstractAntlrTokenToAttributeIdMapper> bindAbstractAntlrTokenToAttributeIdMapper() {
   * return MissionSpecificationAntlrTokenToAttributeIdMapper
   * }
   */
  public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator() {
    return MissionSpecificationSemanticHighlightingCalculator.class;
  }
  
  public MissionSpecificationUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
