/**
 * generated by Xtext 2.10.0
 */
package be.uantwerpen.ansymo.missionspecification.validation;

import be.uantwerpen.ansymo.missionspecification.validation.AbstractMissionSpecificationValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class MissionSpecificationValidator extends AbstractMissionSpecificationValidator {
}
