/**
 * generated by Xtext 2.10.0
 */
package be.uantwerpen.ansymo.missionspecification;

import be.uantwerpen.ansymo.missionspecification.AbstractMissionSpecificationRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MissionSpecificationRuntimeModule extends AbstractMissionSpecificationRuntimeModule {
}
