/**
 * generated by Xtext 2.10.0
 */
package be.uantwerpen.ansymo.missionspecification;

import be.uantwerpen.ansymo.missionspecification.MissionSpecificationStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class MissionSpecificationStandaloneSetup extends MissionSpecificationStandaloneSetupGenerated {
  public static void doSetup() {
    MissionSpecificationStandaloneSetup _missionSpecificationStandaloneSetup = new MissionSpecificationStandaloneSetup();
    _missionSpecificationStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
