/**
 * generated by Xtext 2.10.0
 */
package be.uantwerpen.ansymo.missionspecification.ui.contentassist;

import be.uantwerpen.ansymo.missionspecification.ui.contentassist.AbstractMissionSpecificationProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class MissionSpecificationProposalProvider extends AbstractMissionSpecificationProposalProvider {
}
